import re
from typing import Any, Dict, List, Optional, Union
from .llm_gpt import LLM_gpt
from prompt.instructions import MEMORY_ENCODER_SYSTEM_INSTRUCTION

class ME_agent:
    """
    Memory Encoding Agent for autonomous household robot.
    Encodes raw interaction step observations into structured, concise natural-language memory traces.
    """
    def __init__(self, **kwargs: Any):
        self.llm = LLM_gpt(**kwargs)
        self.system_instruction = MEMORY_ENCODER_SYSTEM_INSTRUCTION

    def encode_observation(self, timestep: int, action: str, observation: str) -> str:
        """
        Takes raw interaction (timestep, action, observation) and generates
        a structured natural-language memory trace.
        """
        obs_clean = observation.strip()
        prompt_content = f"Timestep: {timestep}\nAction: {action}\nObservation: {obs_clean}"

        messages = [
            {"role": "system", "content": self.system_instruction},
            {"role": "user", "content": prompt_content}
        ]
        return self.llm.generate(messages).strip()

    def generate(self, messages: Union[str, List[Dict[str, Any]]]) -> str:
        """ Direct fallback generate method. """
        return self.llm.generate(messages)


class MemoryEncoding:
    """
    Stores and manages structured memory traces generated by ME_agent,
    retrieving top-k closest timestep memories for subtasks during findNplace.
    """
    def __init__(self, me_agent: ME_agent):
        self.me_agent = me_agent
        self.memories: List[Dict[str, Any]] = []

    @staticmethod
    def _normalize_text(text: str) -> str:
        return text.translate(str.maketrans("‘’“”", "''\"\"")).lower()

    @classmethod
    def _extract_target_object_aliases(cls, subtask_desc: str) -> List[str]:
        """
        Extract object aliases from subtasks such as "Find 'butter knife' ...".
        Multi-word object names also get a compact alias, e.g. "butterknife".
        """
        normalized = cls._normalize_text(subtask_desc)
        target_names = re.findall(r"['\"]([^'\"]+)['\"]", normalized)

        if not target_names:
            match = re.search(r"\bfind\s+(.+?)\s+and\s+move\b", normalized)
            if match:
                target_names.append(match.group(1).strip())

        aliases = []
        seen = set()
        for name in target_names:
            cleaned = re.sub(r"\s+", " ", name.strip())
            compact = re.sub(r"[\s_-]+", "", cleaned)
            for alias in (cleaned, compact):
                if alias and alias not in seen:
                    seen.add(alias)
                    aliases.append(alias)

        return aliases

    @staticmethod
    def _contains_alias(text: str, alias: str) -> bool:
        if " " in alias:
            pattern = r"(?<!\w)" + r"\s+".join(re.escape(part) for part in alias.split()) + r"(?!\w)"
        else:
            pattern = rf"(?<!\w){re.escape(alias)}(?!\w)"
        return re.search(pattern, text) is not None

    @classmethod
    def _extract_related_receptacles(cls, text: str, aliases: List[str]) -> List[str]:
        receptacle_pattern = (
            r"\b(?:cabinet|drawer|fridge|microwave|sinkbasin|sink|stoveburner|"
            r"countertop|table|bowl|mug|cup|pot|pan)\s+\d+\b"
        )
        related = []
        seen = set()

        segments = re.split(r"[.;\n]+", text)
        for segment in segments:
            if not any(cls._contains_alias(segment, alias) for alias in aliases):
                continue

            for receptacle in re.findall(receptacle_pattern, segment):
                if receptacle not in seen:
                    seen.add(receptacle)
                    related.append(receptacle)

        if related:
            return related

        for alias in aliases:
            alias_match = re.search(re.escape(alias), text)
            if not alias_match:
                continue

            window_start = max(0, alias_match.start() - 120)
            window_end = min(len(text), alias_match.end() + 120)
            window = text[window_start:window_end]
            for receptacle in re.findall(receptacle_pattern, window):
                if receptacle not in seen:
                    seen.add(receptacle)
                    related.append(receptacle)

        return related

    def encode_and_add_memory(self, timestep: int, action: str, observation: str) -> str:
        """
        Calls ME_agent to encode raw interaction step observation into a structured memory trace, then stores it.
        """
        obs_clean = observation.strip()
        loc_match = re.search(r"arrive at ([a-zA-Z0-9\s]+?)(?=\.|\,|\n|$)", obs_clean, re.IGNORECASE)
        location = loc_match.group(1).strip().lower() if loc_match else None

        encoded_trace = self.me_agent.encode_observation(timestep=timestep, action=action, observation=obs_clean)

        record = {
            "timestep": timestep,
            "action": action,
            "raw_observation": obs_clean,
            "encoded_trace": encoded_trace,
            "location": location,
        }
        self.memories.append(record)
        return encoded_trace

    def retrieve_relevant_memories(
        self,
        subtask_desc: str,
        top_k: int = 3,
        current_timestep: Optional[int] = None,
        max_timestep: Optional[int] = None,
    ) -> List[Dict[str, Any]]:
        """
        Retrieves top_k matching cached memory traces for a given subtask description,
        sorted by closest time step relative to current_timestep.
        If max_timestep is provided, only memories up to that timestep are used.
        """
        if not self.memories or not subtask_desc:
            return []

        stop_words = {
            "the", "a", "an", "and", "or", "to", "in", "on", "inside", "below", "above",
            "from", "next", "top", "right", "left", "bottom", "second", "center",
            "place", "move", "find", "explore", "position", "task", "subtask", "is",
            "your", "begins", "completed", "completed."
        }

        normalized_subtask = self._normalize_text(subtask_desc)
        target_aliases = self._extract_target_object_aliases(subtask_desc)
        target_parts = set()
        for alias in target_aliases:
            target_parts.update(re.findall(r"\b[a-zA-Z0-9]+\b", alias))

        words = re.findall(r"\b[a-zA-Z0-9]+\b", normalized_subtask)
        keywords = [w for w in words if w not in stop_words and len(w) > 1]
        bigrams = [f"{words[i]} {words[i+1]}" for i in range(len(words)-1)]
        search_terms = {
            term for term in set(keywords + bigrams)
            if term not in target_parts
        }

        object_matched_memories = []
        object_match_timesteps = []
        related_receptacles = set()
        candidate_memories = []
        fallback_matched_memories = []
        for mem in self.memories:
            if max_timestep is not None and mem["timestep"] > max_timestep:
                continue

            mem_text = self._normalize_text(
                mem["raw_observation"] + " " + mem["encoded_trace"] + " " + mem["action"]
            )
            action_lower = self._normalize_text(mem["action"])
            candidate_memories.append((mem, mem_text, action_lower))
            is_matched = False
            matched_terms = []

            for alias in target_aliases:
                if self._contains_alias(mem_text, alias):
                    object_matched_memories.append((mem["timestep"], mem, [alias]))
                    object_match_timesteps.append(mem["timestep"])
                    related_receptacles.update(
                        self._extract_related_receptacles(mem_text, target_aliases)
                    )
                    break

            for term in search_terms:
                if term in stop_words:
                    continue
                if (mem["location"] and term in mem["location"]) or (term in mem_text) or (term in action_lower):
                    is_matched = True
                    matched_terms.append(term)

            if is_matched:
                fallback_matched_memories.append((mem["timestep"], mem, list(set(matched_terms))))

        receptacle_context_memories = []
        if object_matched_memories and related_receptacles:
            for mem, mem_text, action_lower in candidate_memories:
                if any(
                    abs(mem["timestep"] - object_ts) <= 3
                    for object_ts in object_match_timesteps
                ) and any(
                    self._contains_alias(mem_text, receptacle)
                    for receptacle in related_receptacles
                ):
                    receptacle_context_memories.append(
                        (mem["timestep"], mem, sorted(related_receptacles))
                    )

        matched_memories = (
            object_matched_memories + receptacle_context_memories
            if object_matched_memories
            else fallback_matched_memories
        )

        # Sort by closest time step to current_timestep (most recent first)
        if current_timestep is not None:
            matched_memories.sort(key=lambda x: abs(current_timestep - x[0]))
        else:
            matched_memories.sort(key=lambda x: x[0], reverse=True)

        results = []
        seen_traces = set()
        for ts, mem, matched in matched_memories:
            trace = mem["encoded_trace"]
            if trace not in seen_traces:
                seen_traces.add(trace)
                results.append({
                    "timestep": ts,
                    "action": mem["action"],
                    "encoded_trace": trace,
                    "location": mem["location"],
                    "matched_terms": matched,
                })
            if len(results) >= top_k:
                break

        return results

    def format_retrieved_memories_prompt(
        self,
        subtask_desc: str,
        top_k: int = 3,
        current_timestep: Optional[int] = None,
        max_timestep: Optional[int] = None,
    ) -> str:
        """
        Formats retrieved memory traces into a structured string ready for injection into decision agent context.
        """
        relevant_mems = self.retrieve_relevant_memories(
            subtask_desc,
            top_k=top_k,
            current_timestep=current_timestep,
            max_timestep=max_timestep,
        )
        if not relevant_mems:
            return ""

        lines = ["* Subtask relevant memories:"]
        for mem in relevant_mems:
            lines.append(f"- Step {mem['timestep']} (Action: '{mem['action']}'): {mem['encoded_trace']}")
        return "\n".join(lines)
